FROM apache/airflow:2.9.3

USER root
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    gcc \
    g++ \
    && rm -rf /var/lib/apt/lists/*

COPY requirements /tmp/requirements
RUN chown -R airflow:0 /tmp/requirements

USER airflow
RUN pip install --no-cache-dir -r /tmp/requirements/airflow.txt

USER root
RUN rm -rf /tmp/requirements

USER airflow